version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rest
      POSTGRES_PASSWORD: rest123456
      POSTGRES_DB: rest_service
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py loaddata fixtures/datadump.json
      && gunicorn django_rest_service.wsgi:application -b 0.0.0.0:8080
      "
    depends_on:
      - db