# Generated by Django 3.1.7 on 2021-04-11 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_TODO', '0002_auto_20210306_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
